import type { AppData } from './types'

export const INITIAL_DATA: AppData = {
  locaties: {
    marsdijk:    { id:'marsdijk',    naam:'Sporthal De Marsdijk',      plaats:'Assen',  adres:'Wisselmarke 1, 9405 KA Assen',         velden:3 },
    palet:       { id:'palet',       naam:'Sporthal Het Palet',        plaats:'Vries',  adres:'De Fledders 17, 9481 AD Vries',        velden:2 },
    boerhoorn:   { id:'boerhoorn',   naam:'MFA De Boerhoorn',          plaats:'Rolde',  adres:'Schoolstraat 5, 9451 AX Rolde',        velden:2 },
    kloosterveen:{ id:'kloosterveen',naam:'Sportcentrum Kloosterveen', plaats:'Assen',  adres:'Het Vaartveld 2, 9408 BR Assen',       velden:3 },
    peelo:       { id:'peelo',       naam:'Sporthal Peelo',            plaats:'Assen',  adres:'Vivaldistraat 2, 9402 HV Assen',       velden:2 },
    demarke:     { id:'demarke',     naam:'Sporthal De Marke',         plaats:'Beilen', adres:'De Vorrelvenne 8, 9411 JE Beilen',     velden:2 },
    norg:        { id:'norg',        naam:'Sporthal De Huurne',        plaats:'Norg',   adres:'Langeloërweg 22, 9331 BC Norg',        velden:1 },
    smilde:      { id:'smilde',      naam:'MFC De Spil',               plaats:'Smilde', adres:'Hoofdweg 9, 9422 AB Smilde',           velden:2 },
  },
  teams: {
    vries1:  { id:'vries1',  naam:'Set Up Vries 1',  kort:'SUV', plaats:'Vries',  hue:212, poule_id:'A', locatie_id:'palet',       avond:'maandag',  start:'20:00', adres:'Brinkweg 14, 9481 BG Vries', aanvoerder:{ naam:'Mark Holtkamp',  tel:'06-12345678', mail:'mark@setupvries.nl' },   blokkades:[] },
    assen2:  { id:'assen2',  naam:'VV Assen Mix 2',  kort:'VVA', plaats:'Assen',  hue:28,  poule_id:'A', locatie_id:'marsdijk',    avond:'dinsdag',  start:'20:15', adres:'Stationsstraat 88, 9401 KZ Assen', aanvoerder:{ naam:'Sanne de Vries', tel:'06-23456789', mail:'sanne@vvassen.nl' }, blokkades:[{ id:'b1', van:'2026-04-25', tot:'2026-05-10', reden:'Meivakantie' }] },
    rolde:   { id:'rolde',   naam:'Rolder Smashers', kort:'ROL', plaats:'Rolde',  hue:265, poule_id:'A', locatie_id:'boerhoorn',   avond:'woensdag', start:'20:00', adres:'', aanvoerder:{ naam:'Jeroen Bakker',  tel:'06-34567890', mail:'jeroen@roldersmashers.nl' }, blokkades:[] },
    kloos1:  { id:'kloos1',  naam:'Kloosterveen 1',  kort:'KLV', plaats:'Assen',  hue:150, poule_id:'A', locatie_id:'kloosterveen',avond:'donderdag',start:'20:30', adres:'', aanvoerder:{ naam:'Lisa Pol',       tel:'06-45678901', mail:'lisa@kloosterveenvc.nl' },    blokkades:[] },
    peelo:   { id:'peelo',   naam:'Peelo Power',     kort:'PEE', plaats:'Assen',  hue:330, poule_id:'A', locatie_id:'peelo',       avond:'dinsdag',  start:'19:30', adres:'', aanvoerder:{ naam:'Tim Wolters',    tel:'06-56789012', mail:'tim@peelopower.nl' },           blokkades:[] },
    smilde:  { id:'smilde',  naam:'Smilde Smash',    kort:'SMI', plaats:'Smilde', hue:48,  poule_id:'A', locatie_id:'smilde',      avond:'maandag',  start:'20:00', adres:'', aanvoerder:{ naam:'Karin Smit',     tel:'06-67890123', mail:'karin@smildesmash.nl' },       blokkades:[] },
    norg:    { id:'norg',    naam:'Norg Net Zes',    kort:'NOR', plaats:'Norg',   hue:188, poule_id:'A', locatie_id:'norg',        avond:'woensdag', start:'20:15', adres:'', aanvoerder:{ naam:'Peter Hof',      tel:'06-78901234', mail:'peter@norgnetzes.nl' },         blokkades:[] },
    beilen3: { id:'beilen3', naam:'Beiler Bal 3',    kort:'BB3', plaats:'Beilen', hue:96,  poule_id:'A', locatie_id:'demarke',     avond:'donderdag',start:'20:00', adres:'', aanvoerder:{ naam:'Anouk Veen',     tel:'06-89012345', mail:'anouk@beilerbal.nl' },          blokkades:[] },
    vries2:  { id:'vries2',  naam:'Set Up Vries 2',  kort:'SU2', plaats:'Vries',  hue:212, poule_id:'B', locatie_id:'palet',       avond:'maandag',  start:'21:00', adres:'', aanvoerder:{ naam:'Bram Dijk',      tel:'06-11112222', mail:'bram@setupvries.nl' },           blokkades:[] },
    assen3:  { id:'assen3',  naam:'VV Assen Mix 3',  kort:'VA3', plaats:'Assen',  hue:28,  poule_id:'B', locatie_id:'marsdijk',    avond:'dinsdag',  start:'21:15', adres:'', aanvoerder:{ naam:'Eva Mulder',     tel:'06-22223333', mail:'eva@vvassen.nl' },               blokkades:[] },
    gieten:  { id:'gieten',  naam:'Gieten Gym',      kort:'GIE', plaats:'Gieten', hue:300, poule_id:'B', locatie_id:'boerhoorn',   avond:'woensdag', start:'19:30', adres:'', aanvoerder:{ naam:'Ruben Kok',      tel:'06-33334444', mail:'ruben@gietengym.nl' },          blokkades:[] },
    loon:    { id:'loon',    naam:'Loon Lobs',       kort:'LOO', plaats:'Loon',   hue:128, poule_id:'B', locatie_id:'peelo',       avond:'donderdag',start:'20:00', adres:'', aanvoerder:{ naam:'Femke Boer',     tel:'06-44445555', mail:'femke@loonlobs.nl' },           blokkades:[] },
  },
  poules: {
    A: { id:'A', naam:'Poule A', niveau:'Niveau 1 · gevorderd', competitie_id:'mix2526' },
    B: { id:'B', naam:'Poule B', niveau:'Niveau 2 · midden',    competitie_id:'mix2526' },
    C: { id:'C', naam:'Poule C', niveau:'Niveau 3 · instap',    competitie_id:'mix2526' },
  },
  competities: {
    mix2526: { id:'mix2526', naam:'Mix Competitie', type:'mix', format:'enkel', seizoen:'2025–2026', startDatum:'2025-09-01', eindDatum:'2026-06-30' },
  },
  standen: {
    A: [
      { team_id:'vries1',  poule_id:'A', g:10, w:8, v:2, sv:27, st:11, pnt:27 },
      { team_id:'rolde',   poule_id:'A', g:10, w:7, v:3, sv:25, st:14, pnt:25 },
      { team_id:'assen2',  poule_id:'A', g:10, w:6, v:4, sv:22, st:17, pnt:22 },
      { team_id:'kloos1',  poule_id:'A', g:10, w:6, v:4, sv:21, st:18, pnt:21 },
      { team_id:'peelo',   poule_id:'A', g:10, w:5, v:5, sv:19, st:19, pnt:19 },
      { team_id:'smilde',  poule_id:'A', g:10, w:4, v:6, sv:16, st:22, pnt:16 },
      { team_id:'norg',    poule_id:'A', g:10, w:2, v:8, sv:12, st:26, pnt:12 },
      { team_id:'beilen3', poule_id:'A', g:10, w:2, v:8, sv:11, st:27, pnt:11 },
    ],
    B: [
      { team_id:'vries2', poule_id:'B', g:6, w:5, v:1, sv:16, st:6,  pnt:16 },
      { team_id:'loon',   poule_id:'B', g:6, w:4, v:2, sv:14, st:9,  pnt:14 },
      { team_id:'assen3', poule_id:'B', g:6, w:2, v:4, sv:10, st:13, pnt:10 },
      { team_id:'gieten', poule_id:'B', g:6, w:1, v:5, sv:7,  st:19, pnt:7  },
    ],
    C: [],
  },
  wedstrijden: [
    { id:'w01', poule_id:'A', thuis_id:'vries1', uit_id:'norg',    datum:'2026-03-02', tijd:'20:00', locatie_id:'palet',        status:'gespeeld', uitslag:[3,1] },
    { id:'w02', poule_id:'A', thuis_id:'rolde',  uit_id:'beilen3', datum:'2026-03-04', tijd:'20:00', locatie_id:'boerhoorn',    status:'gespeeld', uitslag:[3,0] },
    { id:'w03', poule_id:'A', thuis_id:'peelo',  uit_id:'kloos1',  datum:'2026-03-03', tijd:'19:30', locatie_id:'peelo',        status:'gespeeld', uitslag:[1,3] },
    { id:'w04', poule_id:'A', thuis_id:'smilde', uit_id:'assen2',  datum:'2026-03-02', tijd:'20:00', locatie_id:'smilde',       status:'gespeeld', uitslag:[2,3] },
    { id:'w05', poule_id:'A', thuis_id:'assen2', uit_id:'rolde',   datum:'2026-03-10', tijd:'20:15', locatie_id:'marsdijk',     status:'gespeeld', uitslag:null },
    { id:'w06', poule_id:'A', thuis_id:'assen2', uit_id:'vries1',  datum:'2026-03-17', tijd:'20:15', locatie_id:'marsdijk',     status:'gepland',  uitslag:null },
    { id:'w07', poule_id:'A', thuis_id:'kloos1', uit_id:'norg',    datum:'2026-03-19', tijd:'20:30', locatie_id:'kloosterveen', status:'gepland',  uitslag:null },
    { id:'w08', poule_id:'A', thuis_id:'rolde',  uit_id:'peelo',   datum:'2026-03-18', tijd:'20:00', locatie_id:'boerhoorn',    status:'gepland',  uitslag:null },
    { id:'w09', poule_id:'A', thuis_id:'smilde', uit_id:'beilen3', datum:'2026-03-16', tijd:'20:00', locatie_id:'smilde',       status:'verzoek',  uitslag:null,
      verzoek:{ door:'beilen3', aan:'smilde', reden:'Te weinig spelers beschikbaar (vakantie)', nieuweDatum:'2026-03-30', nieuweTijd:'20:00' } },
    { id:'w10', poule_id:'A', thuis_id:'norg',    uit_id:'vries1', datum:'2026-03-25', tijd:'20:15', locatie_id:'norg',         status:'gepland',  uitslag:null },
    { id:'w11', poule_id:'A', thuis_id:'beilen3', uit_id:'assen2', datum:'2026-03-26', tijd:'20:00', locatie_id:'demarke',      status:'gepland',  uitslag:null },
    { id:'w12', poule_id:'A', thuis_id:'peelo',   uit_id:'smilde', datum:'2026-03-24', tijd:'19:30', locatie_id:'peelo',        status:'gepland',  uitslag:null },
    { id:'w13', poule_id:'A', thuis_id:'norg',    uit_id:'assen2', datum:'2026-04-01', tijd:'20:15', locatie_id:'norg',         status:'verzoek',  uitslag:null,
      verzoek:{ door:'norg', aan:'assen2', reden:'Hal niet beschikbaar i.v.m. onderhoud', nieuweDatum:'2026-04-08', nieuweTijd:'20:15' } },
    { id:'w20', poule_id:'B', thuis_id:'vries2', uit_id:'gieten',  datum:'2026-03-09', tijd:'21:00', locatie_id:'palet',        status:'gespeeld', uitslag:[3,1] },
    { id:'w21', poule_id:'B', thuis_id:'loon',   uit_id:'assen3',  datum:'2026-03-19', tijd:'20:00', locatie_id:'peelo',        status:'gepland',  uitslag:null },
  ],
}

export const DEMO_CAPTAIN_TEAM = 'assen2'
